POST http://localhost:3000/actor.json
Content-Type: application/json

{
  "id": 1
}

###

POST http://localhost:3000/m_create.json
Content-Type: application/json

{
  "title": " ",
  "year": 1,
  "plot": " ",
  "gender": " "
}

###

PATCH http://localhost:3000/m_update.json
Content-Type: application/json

{
  "id": 2,
  "title": " "
}

###

DELETE http://localhost:3000/m_delete/1.json
Content-Type: application/json